name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main  

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
      - uses: actions/checkout@v2

      - name: Setup .NET Core
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.0
      
      name: Checkout ParkingLotAPI
        run: cd ParkingLotAPI
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --no-restore

      - name: Publish the application
        run: dotnet publish --configuration Release --output ../app --no-build --no-restore
      
      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      - name: Build Docker image
      run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }}:latest -f ./Dockerfile .

      - name: Push Docker image to Amazon ECR
        run: |
          docker tag ${{ secrets.ECR_REPOSITORY }}:latest ${{secrets.ECR_REPOSITORY }}:latest
          docker push ${{ secrets.ECR_REPOSITORY }}:latest

      